POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "WORST BLOG EVER",
    "author": "worst author ever",
    "url": "worst blogs ever",
    "userId": "675b3a868064c30fd58ae05e",
    "likes": 1
}