# fly.toml app configuration file generated for ivaninandan-phonebook on 2024-10-31T14:26:28-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'ivaninandan-phonebook'
primary_region = 'lax'

[build]

[env]
  PORT = '8080'
  MONGODB_URI = 'mongodb+srv://iinandan97:b9Hjref217909y!@phonebook.9sqxg.mongodb.net/phonebookApp?retryWrites=true&w=majority&appName=phonebook'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
